#!/usr/bin/env python3
"""
Build a professional, narrated demo video for the project.

Composes the already-rendered footage (flat $1M simulation, dynamic-thinking
simulation, real Serie A walk-forward replay) with AI voice narration
generated by Microsoft Edge neural voices (edge-tts, free, no API key) into
a single self-contained MP4 that a stranger can watch without reading a word.

Structure (approximate, timed to each clip):

    [title card]      what this is, in one breath
    [flat sim]        the $1M question: the trained model bets 1200 matches
    [dynamic sim]     the confidence-aware thinking layer
    [serie A replay]  the same machinery on real 2025/26 data
    [outro card]      honest bottom line + how to run it

Only statements that are true of the actual repo are narrated.  No
fabricated numbers.

Run:
    python demo/make_narrated_demo.py

Output: demo/output/demo_narrated.mp4  (+ narration audio under .embed_tmp/)
Dependencies: edge-tts (pip), imageio-ffmpeg (ships the ffmpeg binary).
"""

from __future__ import annotations

import asyncio
import subprocess
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

import imageio_ffmpeg  # noqa: E402

FFMPEG = imageio_ffmpeg.get_ffmpeg_exe()
OUT = Path(__file__).resolve().parent / "output"
TMP = OUT / ".embed_tmp"
TMP.mkdir(parents=True, exist_ok=True)

VOICE = "en-US-BrianNeural"      # clear, professional male voice
RATE = "-4%"                      # slightly slower for a demo read
PITCH = "+0Hz"

# ---------------------------------------------------------------------------
# Narration script.  Every claim is true of the repo as committed.
# ---------------------------------------------------------------------------
# (label, video file or None for a card, narration text)
SECTIONS = [
    ("intro", None, (
        "This is a quantitative machine-learning system for sports betting. "
        "It prices football matches with a Poisson and Elo hybrid, blends in "
        "gradient boosting, learns how much to stake with Q-learning, and "
        "adapts online when the world changes. Every number you are about to "
        "see comes from actually running the code in this repository."
    )),
    ("flat", "simulation_live_flat.mp4", (
        "Here is the one million dollar question. A million dollars, flat "
        "staking, twelve hundred simulated matches — roughly three years of "
        "fixtures. Each green dot is a winning bet, each red dot a losing "
        "bet, sized by the stake. Watch the equity curve move, match by "
        "match, as the model hunts for value against the bookmaker."
    )),
    ("dynamic", "simulation_live_dynamic.mp4", (
        "This is the same simulation, but every decision now flows through "
        "the dynamic thinking layer. It fuses the model's probability with "
        "the sharp market line, watches the public-versus-sharp split, "
        "tracks fatigue, and re-weights its own reasoning from rolling "
        "calibration. It is confidence-aware: sure picks commit bigger "
        "stakes, and it refits its base model whenever its confidence decays."
    )),
    ("seriea", "serie_a_live.mp4", (
        "The same machinery, replayed on real data. This is a point-in-time "
        "walk-forward over actual Serie A 2025-26 matches — the agent never "
        "sees a result before kickoff, and every bet is audited for leakage. "
        "This is how the project validates itself honestly."
    )),
    ("outro", None, (
        "The honest bottom line. Inside the synthetic world, the bookmaker "
        "carries a real margin, and the model does not beat it on average — "
        "the median path loses about six percent. That is the point. The "
        "project is a rigorous, leak-free testing methodology: real odds, "
        "calibrated models, Monte-Carlo distributions, and an audited "
        "walk-forward agent. Run it yourself with the commands in the "
        "readme, and watch the model think in real time."
    )),
]


def card_path(label: str) -> Path:
    """Render a simple title card PNG with matplotlib (matches video style)."""
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    titles = {
        "intro": ("QUANTITATIVE SPORTS-BETTING ML SYSTEM",
                  ["Poisson + Elo  ->  Gradient Boosting  ->  Q-Learning",
                   "->  adaptive online learning  ->  dynamic thinking",
                   "->  leak-free walk-forward validation",
                   "narrated demo · real outputs from the repository"]),
        "outro": ("HONEST BOTTOM LINE",
                  ["synthetic world: median path loses ~6% (P(profit) 32%)",
                   "real data: audited, leak-free walk-forward",
                   "the value is the rigorous methodology, not fake returns",
                   "clone, pip install, and run it yourself"]),
    }
    title, lines = titles[label]
    fig = plt.figure(figsize=(16, 9), facecolor="#101623")
    ax = fig.add_axes([0, 0, 1, 1])
    ax.axis("off")
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    ax.text(0.5, 0.78, title, color="white", fontsize=34, fontweight="bold",
            ha="center", va="center")
    ax.plot([0.30, 0.70], [0.66, 0.66], color="#06D6A0", linewidth=3,
            transform=ax.transAxes)
    for i, ln in enumerate(lines):
        ax.text(0.5, 0.56 - i * 0.08, ln, color="#DCE4EE", fontsize=16,
                ha="center", va="center", family="DejaVu Sans Mono",
                transform=ax.transAxes)
    p = TMP / f"card_{label}.png"
    fig.savefig(p, dpi=100)
    plt.close(fig)
    return p


async def synth(label: str, text: str) -> Path:
    """Generate narration MP3 for one section with edge-tts."""
    import edge_tts

    out = TMP / f"narration_{label}.mp3"
    communicate = edge_tts.Communicate(text, VOICE, rate=RATE, pitch=PITCH)
    await communicate.save(str(out))
    return out


def probe_duration(path: Path) -> float:
    """Return media duration in seconds via ffprobe (from ffmpeg binary)."""
    out = subprocess.run(
        [FFMPEG, "-i", str(path), "-f", "null", "-"],
        capture_output=True, text=True)
    stderr = out.stderr
    for line in stderr.splitlines():
        if "Duration:" in line:
            tok = line.split("Duration:")[1].split(",")[0].strip()
            h, m, s = tok.split(":")
            return int(h) * 3600 + int(m) * 60 + float(s)
    return 0.0


def build_video(card_seconds: float = 8.0):
    """Assemble the demo: cards + clips, then mix narration audio on top.

    Each narration segment is delayed to the start of its video segment.
    Intro/outro cards are held long enough to fit their narration (so two
    voices never overlap), clips play at real speed.
    """
    # 1) narration audio per section (fixed order)
    segments = []
    for label, clip, text in SECTIONS:
        audio = asyncio.run(synth(label, text))
        dur = probe_duration(audio)
        segments.append((label, clip, audio, dur))

    print("Narration segments (label, clip, seconds):")
    for label, clip, audio, dur in segments:
        print(f"  {label:<9} {str(clip or 'CARD'):<32} {dur:6.1f}s")

    # 2) video timeline: cards hold long enough for their narration
    #    (card_seconds at minimum), clips play at real speed.
    timeline = []
    t = 0.0
    for label, clip, audio, dur in segments:
        if clip is None:
            seg_dur = max(card_seconds, dur + 1.5)
        else:
            seg_dur = probe_duration(OUT / clip)
        timeline.append((label, t, seg_dur))
        t += seg_dur
    print("\nVideo timeline (label, start, duration):")
    for label, t0, d in timeline:
        print(f"  {label:<9} {t0:7.1f}s  {d:6.1f}s")

    # 3) inputs: cards as looped PNG (with -t), clips as mp4
    inputs = []
    n_video = 0
    for (label, clip, audio, dur), (_, t0, seg_dur) in zip(segments, timeline):
        if clip is None:
            card = card_path(label)
            inputs += ["-loop", "1", "-t", f"{seg_dur:.3f}", "-i", str(card)]
        else:
            inputs += ["-i", str(OUT / clip)]
        n_video += 1

    # 4) filtergraph: normalise every video to 1600x900@24fps, then concat
    filter_parts = []
    for i in range(n_video):
        filter_parts.append(
            f"[{i}:v]setsar=1,fps=24,"
            f"scale=1600:900:force_original_aspect_ratio=decrease,"
            f"pad=1600:900:(ow-iw)/2:(oh-ih)/2,format=yuv420p[v{i}]")
    concat_in = "".join(f"[v{i}]" for i in range(n_video))
    filter_parts.append(f"{concat_in}concat=n={n_video}:v=1:a=0[outv]")

    # 5) narration audio: each "-i path" pair is ONE input file, so audio k
    #    is input file index n_video + k.  Delay each segment to its video
    #    segment start, then mix.
    audio_inputs = []
    for k, (label, clip, audio, dur) in enumerate(segments):
        audio_inputs += ["-i", str(audio)]
        stream_idx = n_video + k
        t0 = timeline[k][1]
        delay_ms = int(t0 * 1000)
        filter_parts.append(f"[{stream_idx}:a]aresample=24000,adelay={delay_ms}|{delay_ms},"
                            f"apad[a{k}]")

    mix_in = "".join(f"[a{k}]" for k in range(len(segments)))
    filter_parts.append(f"{mix_in}amix=inputs={len(segments)}:normalize=0,"
                        f"atrim=0:{t:.2f},asetpts=PTS-STARTPTS[outa]")
    filter_complex = ";".join(filter_parts)

    out_path = OUT / "demo_narrated.mp4"
    cmd = [FFMPEG, "-y"] + inputs + audio_inputs
    cmd += ["-filter_complex", filter_complex,
            "-map", "[outv]", "-map", "[outa]",
            "-c:v", "libx264", "-preset", "medium", "-crf", "20",
            "-pix_fmt", "yuv420p",
            "-c:a", "aac", "-b:a", "160k", "-shortest",
            str(out_path)]
    print("\nRunning ffmpeg composition (this can take a couple of minutes)...")
    res = subprocess.run(cmd, capture_output=True, text=True)
    if res.returncode != 0:
        print(res.stderr[-3000:])
        raise SystemExit(f"ffmpeg failed: {res.returncode}")
    print(f"\n[OK] Narrated demo saved: {out_path}")
    print(f"     duration: {probe_duration(out_path):.1f}s")
    return out_path


if __name__ == "__main__":
    build_video()
